import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";

export default function Settings() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const handleLogout = async () => { await logout(); navigate("/"); };

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1 className="page-title">Settings</h1>
          <p className="page-sub">Account · preferences · legal information</p>
        </div>
      </div>

      <div className="card settings-card">
        <div className="settings-section-title">Account</div>
        <div className="settings-row">
          <div className="settings-label">Email</div>
          <div className="settings-value">{user?.email}</div>
        </div>
        <div className="settings-row">
          <div className="settings-label">Access Level</div>
          <div className="settings-value">
            <span className="badge-pill green">Approved Beta</span>
          </div>
        </div>
        <div className="settings-row">
          <div className="settings-label">Platform</div>
          <div className="settings-value">SomaSync AI · AALIYAH.IO</div>
        </div>
        <div className="settings-row border-none">
          <div className="settings-label">Version</div>
          <div className="settings-value">MVP Beta 0.1.0</div>
        </div>
      </div>

      <div className="card settings-card" style={{ borderLeft: "3px solid var(--orange)" }}>
        <div className="settings-section-title">⚠ Beta Testing Notice</div>
        <p className="settings-body-text">
          SomaSync AI is currently in a closed beta testing phase. You have been granted
          access as an approved beta tester. Features may change, break, or be removed
          without notice. Your feedback is valuable — please report any issues directly.
        </p>
      </div>

      <div className="card settings-card">
        <div className="settings-section-title">Legal & AI Disclaimers</div>
        <p className="settings-body-text">
          <strong style={{color:"var(--ink)"}}>AI-Generated Content:</strong> All SOAP notes, ICD-10-CM references, and
          clinical documentation produced by SomaSync AI are generated by artificial intelligence
          and are provided as suggestions only. They may contain errors, omissions, or clinically
          inaccurate information.
        </p>
        <p className="settings-body-text" style={{ marginTop: 12 }}>
          <strong style={{color:"var(--ink)"}}>Not Medical Advice:</strong> SomaSync AI does not provide medical advice,
          diagnosis, or treatment. All AI-generated outputs must be reviewed, verified, and
          approved by a licensed clinician before use in any clinical, billing, legal, or
          insurance context.
        </p>
        <p className="settings-body-text" style={{ marginTop: 12 }}>
          <strong style={{color:"var(--ink)"}}>Clinical Documentation:</strong> Verify every AI-generated reference and draft against current official guidance, supporting documentation, and the requirements that apply to your practice. Practitioners are solely responsible for compliance with applicable professional, federal, and state requirements.
        </p>
        <p className="settings-body-text" style={{ marginTop: 12 }}>
          <strong style={{color:"var(--ink)"}}>Privacy:</strong> This beta is not configured for PHI or client-identifying information. Do not enter or dictate names, initials, dates of birth, contact details, medical-record numbers, insurance details, appointment dates, addresses, exact locations, or other identifying information.
        </p>
        <p className="settings-body-text" style={{ marginTop: 12 }}>
          <strong style={{color:"var(--ink)"}}>Limitation of Liability:</strong> To the maximum extent permitted by law,
          AALIYAH.IO shall not be liable for any damages arising from reliance on AI-generated
          outputs from this platform.
        </p>
      </div>

      <div className="card settings-card">
        <div className="settings-section-title">Session</div>
        <button className="btn-signout" onClick={handleLogout}>Sign Out of Dashboard</button>
      </div>
    </div>
  );
}
