import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { AlertCircle } from "lucide-react";

export default function Settings() {
  const { profile, signOut } = useAuth();

  const handleSignOut = async () => {
    await signOut();
  };

  return (
    <div className="space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Settings</h1>
        <p className="text-muted-foreground mt-2">Account · preferences · legal information</p>
      </div>

      {/* Account */}
      <Card>
        <CardHeader>
          <CardTitle>Account</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="flex justify-between items-center py-3 border-b">
            <span className="text-sm font-medium text-muted-foreground">Email</span>
            <span className="text-sm font-semibold">{profile?.email || "—"}</span>
          </div>
          <div className="flex justify-between items-center py-3 border-b">
            <span className="text-sm font-medium text-muted-foreground">Full Name</span>
            <span className="text-sm font-semibold">{profile?.fullName || "—"}</span>
          </div>
          <div className="flex justify-between items-center py-3 border-b">
            <span className="text-sm font-medium text-muted-foreground">Access Level</span>
            <span className="inline-flex items-center rounded-full bg-green-100 px-3 py-1 text-xs font-medium text-green-800">
              Approved Beta
            </span>
          </div>
          <div className="flex justify-between items-center py-3">
            <span className="text-sm font-medium text-muted-foreground">Platform</span>
            <span className="text-sm font-semibold">SomaSync AI · AALIYAH.IO</span>
          </div>
        </CardContent>
      </Card>

      {/* Beta notice */}
      <Card className="border-l-4 border-l-orange-500">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertCircle className="h-5 w-5 text-orange-500" />
            Beta Testing Notice
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground leading-relaxed">
            SomaSync AI is currently in a closed beta testing phase. You have been granted
            access as an approved beta tester. Features may change, break, or be removed
            without notice. Your feedback is valuable — please report any issues directly.
          </p>
        </CardContent>
      </Card>

      {/* Legal / Disclaimers */}
      <Card>
        <CardHeader>
          <CardTitle>Legal & AI Disclaimers</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-sm text-muted-foreground">
          <div>
            <p className="font-semibold text-foreground mb-1">AI-Generated Content</p>
            <p>
              All SOAP notes, ICD-10 codes, CPT codes, and clinical documentation produced by
              SomaSync AI are generated by artificial intelligence and are provided as suggestions
              only. They may contain errors, omissions, or clinically inaccurate information.
            </p>
          </div>

          <div>
            <p className="font-semibold text-foreground mb-1">Not Medical Advice</p>
            <p>
              SomaSync AI does not provide medical advice, diagnosis, or treatment. All
              AI-generated outputs must be reviewed, verified, and approved by a licensed
              clinician before use in any clinical, billing, legal, or insurance context.
            </p>
          </div>

          <div>
            <p className="font-semibold text-foreground mb-1">Billing & Coding</p>
            <p>
              ICD-10 and CPT code suggestions are not guaranteed to be accurate or appropriate
              for any specific payer. Practitioners are solely responsible for compliance with
              applicable federal, state, and payer regulations.
            </p>
          </div>

          <div>
            <p className="font-semibold text-foreground mb-1">Privacy</p>
            <p>
              Do not enter identifiable patient information unless you have confirmed that
              appropriate data use agreements and HIPAA-compliant infrastructure are in place.
            </p>
          </div>

          <div>
            <p className="font-semibold text-foreground mb-1">Limitation of Liability</p>
            <p>
              To the maximum extent permitted by law, AALIYAH.IO shall not be liable for any
              damages arising from reliance on AI-generated outputs from this platform.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* Sign out */}
      <Card>
        <CardHeader>
          <CardTitle>Session</CardTitle>
          <CardDescription>Manage your login session</CardDescription>
        </CardHeader>
        <CardContent>
          <Button variant="destructive" onClick={handleSignOut}>
            Sign Out of Dashboard
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}
