import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';

interface BetaConsentModalProps {
  onAccepted: () => void;
}

export default function BetaConsentModal({ onAccepted }: BetaConsentModalProps) {
  const [scrolled, setScrolled] = useState(false);
  const [accepted, setAccepted] = useState(false);
  const [saving, setSaving] = useState(false);

  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    const el = e.currentTarget;
    if (el.scrollTop + el.clientHeight >= el.scrollHeight - 20) {
      setScrolled(true);
    }
  };

  const handleAccept = async () => {
    if (!accepted || !scrolled) return;
    setSaving(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (session) {
        await supabase.from('beta_signatures').insert({
          user_id: session.user.id,
          email: session.user.email,
          signed_at: new Date().toISOString(),
          version: '1.0',
        });
      }
    } catch (e) {
      // ignore — still let them in
    }
    localStorage.setItem('somasync_beta_accepted', '1');
    setSaving(false);
    onAccepted();
  };

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 9999,
      background: 'rgba(5, 8, 15, 0.95)',
      backdropFilter: 'blur(20px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: '20px',
      fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    }}>
      <div style={{
        background: '#0d1117',
        border: '1px solid rgba(48, 217, 192, 0.2)',
        borderRadius: '16px',
        maxWidth: '640px',
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        maxHeight: '90vh',
        boxShadow: '0 0 80px rgba(48, 217, 192, 0.08), 0 40px 80px rgba(0,0,0,0.6)',
        overflow: 'hidden',
      }}>
        {/* Header */}
        <div style={{
          padding: '28px 32px 20px',
          borderBottom: '1px solid rgba(255,255,255,0.06)',
          flexShrink: 0,
        }}>
          <div style={{
            display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '8px',
          }}>
            <div style={{
              width: '36px', height: '36px', borderRadius: '10px',
              background: 'linear-gradient(135deg, #0aab94, #30d9c0)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: '16px', fontWeight: 900, color: '#061412',
            }}>Λ</div>
            <div>
              <div style={{ fontSize: '11px', color: '#30d9c0', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase' }}>SomaSync AI · ΛΛLIYΛH</div>
              <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.25)', letterSpacing: '0.05em' }}>Beta Access Agreement v1.0</div>
            </div>
          </div>
          <div style={{ fontSize: '18px', fontWeight: 700, color: '#f1f5f9', letterSpacing: '-0.03em' }}>
            Before you begin
          </div>
          <div style={{ fontSize: '12px', color: 'rgba(255,255,255,0.4)', marginTop: '4px', lineHeight: 1.6 }}>
            Read and scroll through the full agreement to continue.
          </div>
        </div>

        {/* Scrollable content */}
        <div
          onScroll={handleScroll}
          style={{
            flex: 1, overflowY: 'auto', padding: '24px 32px',
            fontSize: '12px', lineHeight: '1.9', color: 'rgba(255,255,255,0.55)',
            scrollbarWidth: 'thin', scrollbarColor: 'rgba(48,217,192,0.2) transparent',
          }}
        >
          <Section title="1. Beta Software Disclaimer">
            SomaSync AI is currently in <Highlight>closed beta</Highlight>. Features may be incomplete, unstable, or subject to change without notice. Anthropic AI models and OpenAI Whisper are used under their respective terms of service.
          </Section>

          <Section title="2. Not a Medical Device">
            SomaSync AI is a <Highlight>documentation assistance tool</Highlight> only. It does not diagnose, treat, or replace clinical judgment. All AI-generated SOAP notes, ICD-10 codes, CPT codes, and clinical suggestions must be <Highlight>reviewed, edited, and verified</Highlight> by a licensed practitioner before use in any official capacity.
          </Section>

          <Section title="3. Scope of Practice Responsibility">
            You are solely responsible for ensuring that all documentation, techniques, and billing codes generated by SomaSync AI are within your scope of practice and licensure. SomaSync AI's scope alerts and contraindication flags are informational and do not constitute legal or clinical advice.
          </Section>

          <Section title="4. Data & Privacy">
            Session audio is processed via OpenAI Whisper and is not stored. Generated SOAP notes are stored in your private Supabase account and are not shared with third parties. By using SomaSync AI, you agree not to input patient information that would identify individuals without appropriate patient consent in accordance with HIPAA and applicable state laws.
          </Section>

          <Section title="5. Limitation of Liability">
            ΛΛLIYΛH.IO / SomaSync AI is provided "as is" without warranty of any kind. In no event shall the developers be liable for any clinical, legal, or financial damages arising from use of this software. You assume full responsibility for all clinical decisions made using or informed by this platform.
          </Section>

          <Section title="6. Beta Feedback">
            As a beta tester, you may be asked to provide feedback on your experience. Your feedback helps improve the platform. Participation is voluntary and you may discontinue use at any time.
          </Section>

          <Section title="7. Acceptance">
            By checking the box below and clicking Accept, you confirm that you have read this agreement in full, you are a licensed manual therapy practitioner or supervised student, and you agree to use SomaSync AI responsibly and within your scope of practice.
          </Section>

          {!scrolled && (
            <div style={{
              marginTop: '16px', padding: '10px 14px',
              background: 'rgba(255,159,10,0.08)', border: '1px solid rgba(255,159,10,0.2)',
              borderRadius: '8px', fontSize: '11px', color: '#ff9f0a',
              textAlign: 'center', letterSpacing: '0.02em',
            }}>
              ↓ Scroll to the bottom to continue
            </div>
          )}
        </div>

        {/* Footer */}
        <div style={{
          padding: '20px 32px 28px',
          borderTop: '1px solid rgba(255,255,255,0.06)',
          flexShrink: 0,
        }}>
          <label style={{
            display: 'flex', alignItems: 'flex-start', gap: '12px',
            cursor: scrolled ? 'pointer' : 'not-allowed',
            opacity: scrolled ? 1 : 0.4,
            marginBottom: '16px',
          }}>
            <input
              type="checkbox"
              checked={accepted}
              onChange={e => scrolled && setAccepted(e.target.checked)}
              disabled={!scrolled}
              style={{ marginTop: '2px', accentColor: '#30d9c0', width: '14px', height: '14px', flexShrink: 0 }}
            />
            <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.5)', lineHeight: 1.7 }}>
              I have read and agree to the Beta Access Agreement. I understand this is not a medical device and I am responsible for all clinical decisions.
            </span>
          </label>

          <button
            onClick={handleAccept}
            disabled={!accepted || !scrolled || saving}
            style={{
              width: '100%', padding: '14px',
              background: accepted && scrolled
                ? 'linear-gradient(135deg, #0aab94, #30d9c0)'
                : 'rgba(255,255,255,0.05)',
              border: '1px solid',
              borderColor: accepted && scrolled ? 'transparent' : 'rgba(255,255,255,0.08)',
              borderRadius: '10px',
              color: accepted && scrolled ? '#061412' : 'rgba(255,255,255,0.25)',
              fontSize: '13px', fontWeight: 700,
              cursor: accepted && scrolled && !saving ? 'pointer' : 'not-allowed',
              transition: 'all 0.2s',
              fontFamily: 'inherit',
              letterSpacing: '0.02em',
            }}
          >
            {saving ? 'Saving...' : accepted && scrolled ? 'Accept & Enter SomaSync AI →' : 'Read the full agreement to continue'}
          </button>
        </div>
      </div>

      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600;700&display=swap');
      `}</style>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '20px' }}>
      <div style={{ fontSize: '10px', fontWeight: 700, color: '#30d9c0', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '6px' }}>{title}</div>
      <div>{children}</div>
    </div>
  );
}

function Highlight({ children }: { children: React.ReactNode }) {
  return <span style={{ color: 'rgba(255,255,255,0.8)', fontWeight: 600 }}>{children}</span>;
}
